### PR TITLE
Make make_random_numbers and uuid return a Result

### LINKED ISSUE #248: Return result in uuid/mod
Instead of crashing

https://github.com/rocicorp/repc/blob/ba43e47b33e5e3d32df82823d512fcc5ec831d1b/src/util/uuid/mod.rs#L15

### PR DESCRIPTION
**Pull request by arv**
Fixes #248

### CODE REVIEW

File: src/sync/sync_id.rs [hunk 1]
```diff
@@ -7,7 +7,7 @@ use str_macro::str;
 lazy_static! {
     static ref SESSION_ID: String = {
         let mut randoms: [u8; 4] = [0; 4];
-        uuid::make_random_numbers(&mut randoms);
+        uuid::make_random_numbers(&mut randoms).unwrap();
```
Comment (arv) [inline src/sync/sync_id.rs:10]: We could make `SESSION_ID` a `Result` if we want to be really careful.

Comment (phritz) [reply src/sync/sync_id.rs:10]: i'd just as well ignore the result here and let it default to 0000
```
        let _ = uuid::make_random_numbers(&mut randoms);
```

**Review by phritz — APPROVED** [review]
LGTM
